### ISSUE TITLE
Crumble don't find dynamic params

### ISSUE THREAD

**Issue by pavei** [raphinesse/angular-crumble#7]
URL

http://localhost:3000/users/edit/carlos.lima

```javascript
  $rootScope.$on('$routeChangeSuccess', function() {
        crumble.update();
    });


 $routeProvider.when('/users/edit/:username', {
        controller: "UserEditCtrl",
        templateUrl: 'app/users/edit.html',
        requiredLogin: true,
        label: "Edit User",
        resolve: {
            user : function(UserAdmin, $route){
                return UserAdmin.getUserInformation($route.current.params.username);
            },
            groupsData : function(Group){
                return Group.query().$promise;
            }
        }
    });


Error:

angular.js:12798 Error: Could not find matching route definition for path "/users/edit/"
    at Object.crumble.getCrumb (crumble.js:28)
    at build (crumble.js:50)
    at build (crumble.js:50)
    at Object.crumble.update (crumble.js:16)
    at app.js:63
    at Scope.$broadcast (angular.js:16697)
    at angular-route.js:627
    at processQueue (angular.js:15112)
    at angular.js:15128
    at Scope.$eval (angular.js:16374)

**Comment by raphinesse** [comment]
You either need to add route definitions for the natural parents of your route `/users/edit/:username` or define a custom parent relationship. Both should become clear if you carefully read the docs. If any questions remain after that, feel free to post them here.

**Comment by pavei** [comment]
But when i use this, it works:

```
  $routeProvider.when('/users', {
        templateUrl: 'app/users/index.html',
        requiredLogin: true,
        label: "Users",
        controller: "UserIndexCtrl",
        resolve : {
            usersData: function(UserAdmin){
                return UserAdmin.listUsers();
            }
        }
    });

    $routeProvider.when('/users/new', {
        templateUrl: 'app/users/new.html',
        requiredLogin: true,
        label: "New User",
        controller: "UserNewCtrl",
        resolve: {
            groupsData : function(Group){
                return Group.query().$promise;
            }
        }

    });

**Comment by raphinesse** [comment]
Did you omit a route for `/` in this excerpt, that actually is in your app?  Otherwise this shouldn't work either. However, without a complete but minimal example (you could create one on codepen.io or something similar) I can only guess here.

AFAICT, this has nothing to do with dynamic parameters. What happens when you call `crumble.update` is that crumble builds the breadcrumbs of the current page based on its path. It starts by determining the current page's parent. In your failing case this is `/user/edit`. It then accesses the route definition for that path to get associated meta data (like the label). But the route definition is missing. Which in is exactly what the error message says.

Please be sure to *read the docs carefully* if this is not yet clear to you yet. If you're still convinced that this is a bug, please provide a complete example so I can recreate the problem.

**Comment by pavei** [comment]
With debug i have discover, that i should have an route with complete steps. Do you have any ideia how can i override the getParent function for solving my problem?

Thanks for your time and your help. 

```
 $routeProvider.when('/users/edit', {
           label: "Edit User",
    });



and then

 $routeProvider.when('/users/edit/:username', {
        controller: "UserEditCtrl",
        templateUrl: 'app/users/edit.html',
        requiredLogin: true,
        label: "Edit User",
        resolve: {
            user : function(UserAdmin, $route){
                return UserAdmin.getUserInformation($route.current.params.username);
            },
            groupsData : function(Group){
                return Group.query().$promise;
            }
        }
    });

**Comment by raphinesse** [comment]
It is explained in the [docs](https://github.com/raphinesse/angular-crumble/blob/master/README.md#customizing-the-parent-relationship). You should read them.
