### ISSUE TITLE
crumble forces newest version of angular

### ISSUE THREAD

**Issue by snebjorn** [raphinesse/angular-crumble#9]
I get this error when installing angular-crumble

> Uncaught TypeError: angular.module(...).info is not a function
    at angular-route.js:58
    at Object.ERR_NO_ROUTE (angular-route.js:1224)
    at __webpack_require__ (bootstrap bce38fd556aff15e6609:712)
    at fn (bootstrap bce38fd556aff15e6609:117)
    at Object.<anonymous> (index.js:1)
    at __webpack_require__ (bootstrap bce38fd556aff15e6609:712)
    at fn (bootstrap bce38fd556aff15e6609:117)
    at Object.<anonymous> (index.js:5)
    at __webpack_require__ (bootstrap bce38fd556aff15e6609:712)
    at fn (bootstrap bce38fd556aff15e6609:117)

That basically mean that I have a version mismatch.
It's saying that angular-route isn't the same version as angular.

I have these packages installed:

```json
"dependencies": {
        "angular": "1.4.5",
        "angular-crumble": "^0.2.3",
        "angular-route": "1.4.5"
}
```

I found a solution.

In your index.js you have
```
/* eslint-env node */
'use strict';

// Shim for usage with npm/browserify instead of bower
require('angular-route');
require('./crumble');
module.exports = 'crumble';
```
which makes sense because you have 

**package.json**
```
"dependencies": {
    "angular-route": "^1.2"
  },
```

However that is the root cause of my problem. As I now don't have control over what version of ngRoute is used in your module.

The fix is to remove `require('angular-route');`
```
/* eslint-env node */
'use strict';

// Shim for usage with npm/browserify instead of bower
require('./crumble');
module.exports = 'crumble';
```

It now works :)

I'm no package.json guru. But shouldn't "angular-route" be moved to peer-dependencies in your package.json file?

> Peer Dependencies
What we need is a way of expressing these "dependencies" between plugins and their host package. Some way of saying, "I only work when plugged in to version 1.2.x of my host package, so if you install me, be sure that it's alongside a compatible host." We call this relationship a peer dependency.

**Comment by raphinesse** [comment]
First of all: thanks a lot for this detailed issue and the accompanying PR.

Unfortunately, I cannot reproduce the behavior described in the issue when using [this `package.json`][1]. I always end up with the requested versions of `angular` and `angular-route`. Could you please report what happens when you run `npm test` with the `package.json` linked above?

Only if I omit the dependency to `angular-route`, `crumble`'s dependency on `angular-route@^1.2` will force the latest version of that module. The usefulness of this behavior is questionable but intended.

Your conflict might be caused by a `package-lock.json`. To see if that's the case, you could try a clean install (i.e. remove `node_modules/` and `package-lock.json` before installing).

Please understand that I would rather not change something that is not actually broken, so as to not break any existing installations out there.

[1]: https://gist.github.com/raphinesse/e10c4b2e093ad0c9569b87ec98a7e795

**Comment by snebjorn** [comment]
Found the issue. I'm using YARN which doesn't behave the same way as NPM when it comes to child dependencies. I tried doing a clean install of your example via NPM and YARN

> \> npm i
> \> npm list
> angular-crumble-demo@1.0.0
> +-- angular@1.5.11
> +-- angular-crumble@0.2.3
> | \`-- angular-route@1.5.11 deduped
> \`-- angular-route@1.5.11

> \> yarn
> \> yarn list
> yarn list v1.5.1
> ├─ angular-crumble@0.2.3
> │  ├─ angular-route@^1.2
> │  └─ angular-route@1.6.9
> ├─ angular-route@1.5.11
> └─ angular@1.5.11

Notice that yarn says _angular-route@1.6.9_

Perhaps the behavior your expecting is an undocumented feature of package.json. Or there's a bug in YARN :)

**Comment by snebjorn** [comment]
Appears it's a YARN deduping issue. Found these issues 

- yarnpkg/yarn/issues/5236
- yarnpkg/yarn/issues/3778
- yarnpkg/yarn/issues/1251

**Comment by snebjorn** [comment]
# Workaround
Open **yarn.lock** and find **angular-route@^1.2** and then change *version* and *resolved* to their correct values.

In my case it was:

```
angular-route@^1.2:
  version "1.4.5"
  resolved "https://registry.yarnpkg.com/angular-route/-/angular-route-1.4.5.tgz#59c86e30b8f7771eccc3ea3f7e8c515d5495c3ca"
```

**Comment by raphinesse** [comment]
Thanks again for the great debugging work!

I have given this some more thought. Whether the bad deduping in yarn is considered a bug or not, it is probably a bad idea to rely on the deduping of the package manager for correct behavior of `crumble`. And that means the direct dependency has to go.
